### ISSUE TITLE
Clarify data source and license

### ISSUE THREAD

**Issue by simon04** [JOSM/austriaaddresshelper#1] opened 2016-11-09 19:20 UTC
This plugin is interesting. I assume the data source is http://www.bev.gv.at/portal/page?_pageid=713,2167982&_dad=portal&_schema=PORTAL – am I correct?

Is this data licensed in an OSM compatible way?

**Comment by thomaskonrad** [comment] 2016-11-09 19:32
Yes, you are right @simon04. I got the written permission of the Bundesamt für Eich- und Vermessungswesen to use the data with this plugin. For details see the OpenStreetMap Austria mailing list.

**Comment by thomaskonrad** [comment] 2016-11-09 19:46
See also https://github.com/JOSM/austriaaddresshelper/commit/74602e928101e32200b8f092c344c237f3260dc4.

**Comment by thomaskonrad** [comment] 2016-11-10 08:06
There is a [discussion](https://lists.openstreetmap.org/pipermail/talk-at/2016-November/008596.html) going on on the OpenStreetMap talk-at mailing list on whether it is actually possible to use the data because of the license restrictions. The problem is that the BEV [requires all secondary products to mention the source](http://www.bev.gv.at/portal/page?_pageid=713,1604469&_dad=portal&_schema=PORTAL), which is in fact incompatible with the [ODBL license](http://opendatacommons.org/licenses/odbl/).

As long as this is not clarified, I won't put the plugin on the JOSM plugin list for an automatic installation in JOSM.

**Comment by thomaskonrad** [comment] 2017-03-25 15:12
OpenStreetMap now has the [official permission to use the data](https://wiki.openstreetmap.org/wiki/WikiProject_Austria/%C3%96sterreichisches_Adressregister). Closing this.

**Closed as completed by thomaskonrad** 2017-03-25 15:12 UTC
